Add command check err (#7)

diff --git a/terrascript b/terrascript
--- a/terrascript
+++ b/terrascript
@@ -19,6 +19,22 @@ err () {
   echo -e "[${RED}ERROR${NC}]: $*" >&2
 }
 
+command_check() {
+  for cmd in "$@"; do
+    if type "${cmd}" >/dev/null 2>&1 || [[ -x "${cmd}" ]]; then
+      continue
+    fi
+    ERRORS+=("${cmd}")
+  done
+
+  if [ ${#ERRORS[@]} -ne 0 ]; then
+    for e in "${ERRORS[@]}"; do
+      err "missing ${RED}${e##*/}${NC} command"
+    done
+    exit 1
+  fi
+}
+
 show_version() {
   printf "Terrascript Version: %s\n" "${TERRASCRIPT_VERSION}"
   printf "Git Commit: %s\n" "${GIT_COMMIT:-dev}"
@@ -238,7 +254,7 @@ setup() {
       echo -e "[${RED}DELETED${NC}]: deleted resource ${RED}${path}${NC}"
     done
   else
-    err "These resource failed terraform ${RED}${ERRORS[*]}${NC}"
+    err "These resource failed terrascript ${RED}${ERRORS[*]}${NC}"
     exit 1
   fi
 }
@@ -246,11 +262,9 @@ setup() {
 main() {
   local CONTINUE=1
 
-  if [[ ! -x "${TF_BIN}" ]]; then
-    err "missing terraform command"
-  elif ! type git >/dev/null 2>&1; then
-    err "missing git command"
-  elif [[ $# -eq 0 ]]; then
+  command_check "git" "${TF_BIN}"
+
+  if [[ $# -eq 0 ]]; then
     usage
   else
     for arg in "$@"; do
