Refactor bash script to follow shellguide by google (#5)

diff --git a/terrascript b/terrascript
--- a/terrascript
+++ b/terrascript
@@ -1,16 +1,16 @@
 #!/bin/bash
 TERRASCRIPT_VERSION=v0.1.4
 
-set -eo pipefail
+set -euo pipefail
 
-RED='\033[1;31m'
-YELLOW='\033[1;33m'
-GREEN='\033[1;32m'
-BLUE='\033[1;34m'
-LGREEN='\033[1;92m'
-LYELLOW='\033[1;93m'
-WHITE='\033[1;97m'
-NC='\033[0m'
+declare -xr RED='\033[1;31m'
+declare -xr YELLOW='\033[1;33m'
+declare -xr GREEN='\033[1;32m'
+declare -xr BLUE='\033[1;34m'
+declare -xr LGREEN='\033[1;92m'
+declare -xr LYELLOW='\033[1;93m'
+declare -xr WHITE='\033[1;97m'
+declare -xr NC='\033[0m'
 
 # Terraform variables
 TF_BACKEND=${TF_BACKEND:-aws}
@@ -21,11 +21,15 @@ TF_VALIDATE="$TF_BIN validate"
 TF_PLAN="$TF_BIN plan -out $TF_PLANFILE"
 TF_APPLY="$TF_BIN apply $TF_PLANFILE"
 
-function show_version() {
+err () {
+  echo -e "${RED}Error:${NC} $*" >&2
+}
+
+show_version() {
   printf "Terraform Version: %s\n" "${TERRASCRIPT_VERSION}"
 }
 
-function show_figlet() {
+show_figlet() {
   cat <<EOF
  _______                                _       _
 |__   __|                              (_)     | |
@@ -38,7 +42,7 @@ function show_figlet() {
 EOF
 }
 
-function usage() {
+usage() {
   cat <<EOF
 $(show_figlet)
 
@@ -70,7 +74,7 @@ ENVIRONMENT VARIABLES:
 EOF
 }
 
-function select_backend() {
+select_backend() {
 
   if [ "$1" == "aws" ]; then
     export TF_BACKEND_CONFIG="-backend-config=\"bucket=\$TF_BACKEND_BUCKET\""
@@ -82,10 +86,10 @@ function select_backend() {
   fi
 }
 
-function assigner_check() {
-  assigner=$(echo "$TF_ASSIGNERS" | base64 -d)
+assigner_check() {
+  assigner=$(echo "${TF_ASSIGNERS}" | base64 -d)
 
-  if ! grep "$GITLAB_USER_LOGIN" <<<"${assigner}"; then
+  if ! grep "${GITLAB_USER_LOGIN}" <<<"${assigner}"; then
     echo -e "${WHITE}-------------------------------------${NC}"
     echo -e "${RED}ERROR:${NC} WHOOPS! You are not allowed to run this operation${NC}"
     echo -e "${WHITE}-------------------------------------${NC}"
@@ -98,57 +102,57 @@ function assigner_check() {
 
 }
 
-function execute() {
+execute() {
   local basedir
   local cachedir
+  local target_dirs
+  local action
+  local destroy
 
-  basedir=$PWD
+  basedir="${PWD}"
   cachedir=$(
-    cachedir=${TF_PLUGIN_CACHE_DIR:-/tmp/terraform/plugin-cache}
+    cachedir="${TF_PLUGIN_CACHE_DIR:-/tmp/terraform/plugin-cache}"
     mkdir -p "${cachedir}"
     echo "${cachedir}"
   )
+  target_dirs=$1
+  action=$2
 
-  local _dirs=$1
-  local _action=$2
-  local _ifdestroy
+  if [ -n "${3:-}" ]; then destroy="-destroy"; fi
 
-  if [ -n "$3" ]; then _ifdestroy="-destroy"; fi
-
-  for tfpath in ${_dirs}; do
-    dir_with_files=$(find "$basedir/$tfpath" -maxdepth 1 -type f 2>/dev/null)
-    if [ -n "$dir_with_files" ]; then
-
+  for tfpath in ${target_dirs}; do
+    dir_with_files=$(find "${basedir}"/"${tfpath}" -maxdepth 1 -type f 2>/dev/null)
+    if [ -n "${dir_with_files}" ]; then
       echo -e "${BLUE}[START]${NC} ${WHITE}Starting Terraform task at${NC} ${LYELLOW}$tfpath\n${NC}"
 
       bash -c "
         export TF_BACKEND_STATE=${tfpath%\/}/terraform.tfstate
         export TF_PLUGIN_CACHE_DIR=${cachedir}
 
-        cd $basedir/$tfpath
+        cd ${basedir}/${tfpath}
         sleep 1
 
-        case ${_action} in
+        case ${action} in
           validate)
-          $TF_INIT -backend=false
-          $TF_VALIDATE
-          ;;
+            ${TF_INIT} -backend=false
+            ${TF_VALIDATE}
+            ;;
           plan)
-          $TF_INIT $TF_BACKEND_CONFIG
-          sleep 1
-          $TF_VALIDATE
-          sleep 1
-          $TF_PLAN ${_ifdestroy}
-          ;;
+            ${TF_INIT} ${TF_BACKEND_CONFIG}
+            sleep 1
+            ${TF_VALIDATE}
+            sleep 1
+            ${TF_PLAN} ${destroy}
+            ;;
           apply)
-          $TF_INIT $TF_BACKEND_CONFIG
-          sleep 1
-          $TF_VALIDATE
-          sleep 1
-          $TF_PLAN ${_ifdestroy}
-          sleep 5
-          $TF_APPLY
-          ;;
+            ${TF_INIT} ${TF_BACKEND_CONFIG}
+            sleep 1
+            ${TF_VALIDATE}
+            sleep 1
+            ${TF_PLAN} ${destroy}
+            sleep 5
+            ${TF_APPLY}
+            ;;
         esac
       "
 
@@ -158,7 +162,18 @@ function execute() {
   done
 }
 
-function setup() {
+sp="/-\|"
+sc=0
+
+spin() {
+   printf "\b%s" "${sp:sc++:1}"
+   ((sc==${#sp})) && sc=0
+}
+endspin() {
+   printf "\r%s\n" "$@"
+}
+
+setup() {
   local repo
   local action
   local added_dirs
@@ -166,11 +181,11 @@ function setup() {
   local deleted_dirs
 
   action=$1
-  repo=$(basename "$(git rev-parse --show-toplevel)")
+  repo="$(basename "$(git rev-parse --show-toplevel)")"
 
   # Git commit variables
-  CURRENT_HEAD=$(git rev-parse HEAD)
-  PREVIOUS_HEAD=${TF_PREVIOUS_HEAD:-$(git rev-parse HEAD^1)}
+  CURRENT_HEAD="$(git rev-parse HEAD)"
+  PREVIOUS_HEAD="${TF_PREVIOUS_HEAD:-$(git rev-parse HEAD^1)}"
 
   # Select backend and forming -backend-config arguments for terraform
   select_backend "${TF_BACKEND}"
@@ -179,11 +194,12 @@ function setup() {
   # > Adding
   # > Modified/Renamed
   # > Deleted
+  echo -e "Terraform resources on ${BLUE}${repo}${NC}"
+  added_dirs=$(git --no-pager diff "${PREVIOUS_HEAD}"..."${CURRENT_HEAD}" --dirstat-by-file --diff-filter=A -- '*.tf' '*.tfvars' '*.json' | awk '{ print $2 }'); sleep 1
+  modified_dirs=$(git --no-pager diff "${PREVIOUS_HEAD}"..."${CURRENT_HEAD}" --dirstat-by-file --diff-filter=MR -- '*.tf' '*.tfvars' '*.json' | awk '{ print $2 }'); sleep 1
+  deleted_dirs=$(git --no-pager diff "${PREVIOUS_HEAD}"..."${CURRENT_HEAD}" --dirstat-by-file --diff-filter=D -- '*.tf' '*.tfvars' '*.json' | awk '{ print $2 }'); sleep 1
 
-  added_dirs=$(git --no-pager diff "${PREVIOUS_HEAD}"..."${CURRENT_HEAD}" --dirstat-by-file --diff-filter=A -- '*.tf' '*.tfvars' '*.json' | awk '{ print $2 }')
   if [ -n "${added_dirs}" ]; then
-    echo -e "${BLUE}Terraform resources on ${repo}\n${NC}"
-
     echo -e "${WHITE}-------------------------------------${NC}"
     echo -e "${YELLOW}[ADDED]${NC} Terraform resources list:"
     echo -e "${WHITE}-------------------------------------\n${NC}"
@@ -191,10 +207,7 @@ function setup() {
     execute "${added_dirs[@]}" "${action}"
   fi
 
-  modified_dirs=$(git --no-pager diff "${PREVIOUS_HEAD}"..."${CURRENT_HEAD}" --dirstat-by-file --diff-filter=MR -- '*.tf' '*.tfvars' '*.json' | awk '{ print $2 }')
   if [ -n "${modified_dirs}" ]; then
-    echo -e "${BLUE}Terraform resources on ${repo}\n${NC}"
-
     echo -e "${WHITE}-------------------------------------${NC}"
     echo -e "${GREEN}[MODIFIED]${NC} Terraform resources list:"
     echo -e "${WHITE}-------------------------------------\n${NC}"
@@ -202,10 +215,7 @@ function setup() {
     execute "${modified_dirs[@]}" "${action}"
   fi
 
-  deleted_dirs=$(git --no-pager diff "${PREVIOUS_HEAD}"..."${CURRENT_HEAD}" --dirstat-by-file --diff-filter=D -- '*.tf' '*.tfvars' '*.json' | awk '{ print $2 }')
   if [ -n "${deleted_dirs}" ]; then
-    echo -e "${BLUE}Terraform resources on ${repo}\n${NC}"
-
     echo -e "${WHITE}-------------------------------------${NC}"
     echo -e "${RED}[DELETED]${NC} Terraform resources list:"
     echo -e "${WHITE}-------------------------------------\n${NC}"
@@ -238,17 +248,13 @@ function setup() {
   done
 }
 
-function main() {
+main() {
   local CONTINUE=1
 
-  if [[ ! -x $TF_BIN ]]; then
-    echo -e "${WHITE}-------------------------------------${NC}"
-    echo -e "${RED}ERROR:${NC} missing terraform command"
-    echo -e "${WHITE}-------------------------------------${NC}"
+  if [[ ! -x ${TF_BIN} ]]; then
+    err "missing terraform command"
   elif ! type git >/dev/null 2>&1; then
-    echo -e "${WHITE}-------------------------------------${NC}"
-    echo -e "${RED}ERROR:${NC} missing git command"
-    echo -e "${WHITE}-------------------------------------${NC}"
+    err "missing git command"
   elif [[ $# -eq 0 ]]; then
     usage
   else
@@ -276,12 +282,7 @@ function main() {
         CONTINUE=0
         ;;
       *)
-        echo -e "${WHITE}-------------------------------------${NC}"
-        echo -e "${RED}ERROR:{NC} WHOOPS! Terascript argument ${RED}'$CHOICE'${NC}"
-        echo -e "${RED}is not available yet!${NC}"
-        echo -e "${WHITE}-------------------------------------${NC}"
-        printf "\n\n"
-        usage
+        err "Unexpected argument for ${YELLOW}'$CHOICE'${NC}!"
         break
         ;;
       esac
